### ISSUE TITLE
поиск

### ISSUE THREAD

**Issue by Vladimir855** [GonzoTheDev/BitcoinPublicKeyGrabber#3]
надо выставлять в скрипте таймаут при парсинге на блокчейн, чтобы не пропускал?

**Comment by GonzoTheDev** [comment]
> надо выставлять в скрипте таймаут при парсинге на блокчейн, чтобы не пропускал?


В моем случае в этом не было необходимости, но это может быть для вас в зависимости от вашего варианта использования.

**Comment by Vladimir855** [comment]
проверяет глубину транзакций для поиска ключа к примеру 200 транзакций?

> > надо выставлять в скрипте таймаут при парсинге на блокчейн, чтобы не пропускал?
> 
> В моем случае в этом не было необходимости, но это может быть для вас в зависимости от вашего варианта использования.

для блокчейн нужен тайм - аут 10 секунд чтоб ваш API не блокировался

**Comment by GonzoTheDev** [comment]
I added a 10 second timeout in this commit: [6e48a51b](https://github.com/GonzoTheDev/BitcoinPublicKeyGrabber/commit/6e48a51b7985f1014d5c595434e383d629756cd0)
